### ISSUE TITLE
wrk2 request rates (and the resulting latencies) seem arbitrary and not very realistic

### ISSUE THREAD

**Issue by ztellman** [ptaoussanis/clojure-web-server-benchmarks#29]
I'm mostly looking for a response from @xfeep and @ptaoussanis, but anyone with an opinion should chime in.

It struck me as a bit weird that the latencies were all measured in seconds, but didn't have the time to really look into it before the benchmarks were published.  Apparently our benchmark is simulating an open queueing network with a sustained throughput of 400k qps.  This means that any throughput that falls short of 400k is treated as if it's sitting on a queue, which is getting progressively longer with each passing second.

As far as I know, no one in the Clojure landscape has a system with the above properties.  Some systems at Factual have sustained request rates of 200-250k qps across 4-8 machines, but if the request volume exceeds what it can handle, it returns a 503 status code.  I'd characterize this as a "typical" setup.  Almost any large-scale system I'm aware of uses backpressure or load-shedding, not some infinitely growing queue.

Peak throughput, obviously, can't be measured without choosing some arbitrarily large number (though it looks like the choice of 30k qps for the non-keepalive benchmark may be at least somewhat less than the peak possible throughput, since pretty much everyone achieved that).  But if I'm building a system that's concerned with latency, I won't push the max possible volume through a server, I'll limit it to no more than 80% or so.

A more useful set of benchmarks would be mean and 99.99% latency values for 50k qps, 100k qps, etc.  I know this creates even more of a permutation explosion, but I think the current set of latency values are useless at best, and greatly misleading at worst.  I'd like to seem them replaced with something else as soon as we can agree on what that should be.

**Comment by xfeep** [comment]
@ztellman Thanks for  your deep thought about this issue.

>Peak throughput, obviously, can't be measured without choosing some arbitrarily large number (though it looks like the choice of 30k qps for the non-keepalive benchmark may be at least somewhat less than the peak possible throughput, since pretty much everyone achieved that). 

Because 
1. we do test at the same computer and for non-keepalive benchmark every request will create a new connection and use a tcp port. One computer at most has about 60k tcp ports. 
2. we use the same rate viz. 30k/s both for 1k connections non-keepalive benchmark and 60k non-keepalive benchmark.
So if we increase the rate many connections will be failed.

>A more useful set of benchmarks would be mean and 99.99% latency values for 50k qps, 100k qps, etc. I know this creates even more of a permutation explosion, but I think the current set of latency values are useless at best, and greatly misleading at worst. I'd like to seem them replaced with something else as soon as we can agree on what that should be.

Maybe we really need to do some changes or wait until the probably changes of wrk2 is done  because maybe  its author  will consider modifying the test methodology (please see [HERE](https://github.com/TechEmpower/FrameworkBenchmarks/issues/1220#issuecomment-62671946) ) .

**Comment by ztellman** [comment]
I know there are configurations that can be used to increase the range of ports, but I'm not sure how important that is to benchmark.  I'm not sure, offhand, what the difference between the 1k and 60k benchmarks are if they're all closing the connections after the first response.  Isn't a single client opening 30k connections/sec and 30k clients opening 1 connection/sec functionally equivalent?  And if pretty much every server can handle the resulting 30k qps, what is the benchmark telling us?  It may capture the cost of a TCP handshake over localhost, but again, that doesn't seem very relevant to any real-world use case.

As far as I can tell, the work being discussed in your link is what single scalar value should be used to represent the "speed" of a server.  What's being suggested there seems fine, if a little vague, but my concern is mostly w.r.t. the latency values.  I've run a very simple set of benchmarks on my local machine using Aleph:

```
for x in {5000,10000,15000,20000,25000,30000,35000,40000}; do wrk2 -t2 -c100 -d60s --latency -R $x http://127.0.0.1:8080; done
```

![screen shot 2015-03-29 at 2 50 05 pm](https://cloud.githubusercontent.com/assets/31295/6887977/eb3846ce-d623-11e4-91b9-bd06b2f12bf6.png)

My understanding of the linked conversation is that we would effectively draw a vertical line wherever any of these go over the specified thresholds.  This would be nice as a way to order the servers, but I think it would also be useful to just have a graph like the above for each of the servers, since that will give the best indication of the relative performance of each of the servers, no matter what a person's latency requirements are.

And even if we do decide to wait for the TechEmpower guys to come up with a better performance measurement, I think we should immediately remove the latency graphs, and at least discuss what the relative value of the 1k and 60k non-keepalive benchmarks are.

**Comment by xfeep** [comment]
>I know there are configurations that can be used to increase the range of ports, but I'm not sure how important that is to benchmark.

Yes, but the ephemeral ports range range won't exceed 65k. 

> I'm not sure, offhand, what the difference between the 1k and 60k benchmarks are if they're all closing the connections after the first response. Isn't a single client opening 30k connections/sec and 30k clients opening 1 connection/sec functionally equivalent? 

wrk/wrk2 won't take the initiative to close connections. We use `-H  'Connection: close'` to tell servers to close the connection after every reply. Further more  Please note that option `-c ` in wrk/wrk2 does mean opening connections not clients. So your question turns to be that 
"Isn't a single connection complete 30k qps and every connection of 30k connections complete 1 qps functionally equivalent?". Clearly they are quite different and the later will give a server greater stress. Requests from a single connection will be sent one by one because by default HTTP pipelining is not used.


> And if pretty much every server can handle the resulting 30k qps, what is the benchmark telling us? It may capture the cost of a TCP handshake over localhost, but again, that doesn't seem very relevant to any real-world use case.

They really can handle the resulting 30k qps under 1k non-keeplive connections but they also get different lantency. When under 60k non-keepalive connections none of them can handle 30k qps. So if the qps are mostly same the lantency and error rate will be more important. We use 30k/s rate for both 1k and 60k to make the results can be campared easily. If we are regardless of it we should have use more larger rate with 1k non-keepalive connections and more lower rate with 60k non-keepalive connections.
BTW. 30k/s rate with 60k non-keepalive connections means there are 60k opening collections but only  half of them are active within one second.

**Comment by ztellman** [comment]
I agree that they aren't exactly the same, sorry for the overly broad comment.  I'd still like to hear your thoughts on the sentence you didn't quote, which is that a three-way handshake over localhost is very different to one over an actual network.  I don't know exactly how that would affect the results, but I'm not sure what sort of conclusions someone reading the benchmarks could be expected to make based on those results.

Also, do you see a reason to keep the current latency graphs around?  If not, I'll make a pull request to remove them.  I'd also like to hear your thoughts on the proposed alternative.

**Comment by xfeep** [comment]
>I'd still like to hear your thoughts on the sentence you didn't quote, which is that a three-way handshake over localhost is very different to one over an actual network. 

As I know TCP handshake over localhost is not different from one over an actual network regardless of latency and bandwidth. So I can not catch your thoughts about it. Please tell me more if you have more details.


> I don't know exactly how that would affect the results, but I'm not sure what sort of conclusions someone reading the benchmarks could be expected to make based on those results.

They can see some servers are goot at managing keepalive connections and some of them are not good at large amount of non-keepalive connections. So for those goot at keepalive connections but not good at managing large amount of non-keepalive connections maybe a http reverse proxy ,e.g. haproxy, as its front is a better choice when under large amount of non-keepalive connections.


> Also, do you see a reason to keep the current latency graphs around? If not, I'll make a pull request to remove them. I'd also like to hear your thoughts on the proposed alternative.

Sometimes latency results from wrk2 maybe are 200 times of the one from  wrk (at least before v3.1.1 because I have not try the latest wrk). Maybe they are so depressing but they reflect facts. If they are wrong we should fix them but not hide them. But I agree that our latency results are misleading for those people who are used to the latency results from wrk. They maybe 
will be shocked by so poor latency. So If @ptaoussanis has no objection  I agree to remove them before we find a better way.

**Comment by ztellman** [comment]
It's different in that there's no time spent on the wire, so the latency, throughput, and chance that any two clients open a connection at exactly the same time will be very different.  It's definitely useful to know which machines are best at handling lots of connections opening and closing, I'm just not sure that's what this represents.

As to the results "reflecting facts", my entire point is that they don't.  The current numbers represent a system with an infinitely large queue that has a sustained load of 400k qps.  I don't think there's a system on earth that resembles that description, so the results are misleading for everyone.  I understand what wrk2 is trying to do, and I agree that capturing the effects of coordinated omission is important, but that's not what the current set of benchmarks accomplish.  If you disagree with me on this point, it would help me to understand what you believe the current results represent.

And again, I'd be interested to hear your thoughts on my proposed alternative.

**Comment by xfeep** [comment]
> It's different in that there's no time spent on the wire, so the latency, throughput, and chance that any two clients open a connection at exactly the same time will be very different. It's definitely useful to know which machines are best at handling lots of connections opening and closing, I'm just not sure that's what this represents.

I agree that there's no time spent on the wire, so the latency, throughput, and chance that any two clients open a connection at exactly the same time will be very different. But because we use 30k/s rate for non-keepalive benchmark so tcp layer cost is not the major issue. In fact different servers got different results. If the tcp layer cost is the major issue, all servers would get the mostly same results.

> As to the results "reflecting facts", my entire point is that they don't. The current numbers represent a system with an infinitely large queue that has a sustained load of 400k qps. I don't think there's a system on earth that resembles that description, so the results are misleading for everyone.

There `facts` I mentioned did not have the same meaning with your words above. I mean that if we didn't make any mistake the results are true and the latency results  are really `depressing` when under certain stress. 
I agree that there's a system on earth that resembles that description but I don't agree that the results are misleading for everyone.  Our benchmark is and maybe will always be too simple to reflect our real world but it is enough that the simplicity, to some degree, can reflect some key and meaningful things. Further more I agree 400k/s rate is not ideal. It is ideal if our script can guess a number or use a range of rate instead of only one fixed rate, e.g. 400k/s for keepalive, 30k/s for non-keepalive.
 
> I understand what wrk2 is trying to do, and I agree that capturing the effects of coordinated omission is important, but that's not what the current set of benchmarks accomplish. If you disagree with me on this point, it would help me to understand what you believe the current results represent.
> And again, I'd be interested to hear your thoughts on my proposed alternative.

Here are my opinions

1. Our script can guess a number or use a range of rate just as you mentioned instead of only one fixed rate
2. Use line charts, which have latency and qps as two dimensions, to replace current latency charts.
3.  I agree to remove the latency charts first before the above two things are done.

**Comment by ztellman** [comment]
Okay, thank you for discussing this with me.  I'm sorry if I misunderstood what you meant earlier, and I agree that over-simplified results are unavoidable.  Just to be clear, I'm grateful for all the effort you put into updating the benchmarks, and I'm looking forward to working towards the new benchmarks.

**Comment by xfeep** [comment]
Sorry for typo error 

> I agree that there's a system on earth that resembles that description but I don't agree that the results are misleading for everyone. 

Should be 

>I agree that there's **NO**  system on earth that resembles that description but I don't agree that the results are misleading for everyone. 

But I think you have got it :-)

**Comment by cloudy38** [comment]
> I'm mostly looking for a response from @xfeep and @ptaoussanis, but anyone with an opinion should chime in.
> 
> It struck me as a bit weird that the latencies were all measured in seconds, but didn't have the time to really look into it before the benchmarks were published. Apparently our benchmark is simulating an open queueing network with a sustained throughput of 400k qps. This means that any throughput that falls short of 400k is treated as if it's sitting on a queue, which is getting progressively longer with each passing second.
> 
> As far as I know, no one in the Clojure landscape has a system with the above properties. Some systems at Factual have sustained request rates of 200-250k qps across 4-8 machines, but if the request volume exceeds what it can handle, it returns a 503 status code. I'd characterize this as a "typical" setup. Almost any large-scale system I'm aware of uses backpressure or load-shedding, not some infinitely growing queue.
> 
> Peak throughput, obviously, can't be measured without choosing some arbitrarily large number (though it looks like the choice of 30k qps for the non-keepalive benchmark may be at least somewhat less than the peak possible throughput, since pretty much everyone achieved that). But if I'm building a system that's concerned with latency, I won't push the max possible volume through a server, I'll limit it to no more than 80% or so.
> 
> A more useful set of benchmarks would be mean and 99.99% latency values for 50k qps, 100k qps, etc. I know this creates even more of a permutation explosion, but I think the current set of latency values are useless at best, and greatly misleading at worst. I'd like to seem them replaced with something else as soon as we can agree on what that should be.

Nope i was already prepared. Ive be building little tonky toys on the side redy to unleash them into transformers. See its not the power of your work its the work you put in your power.
